<html>
 <footer class="site-footer">
        <p>Copyright 2025, The Swinburne Sigmas. All rights reserved.</p>
        <a href="https://webtechprojectteam.atlassian.net/jira/software/projects/SCRUM/boards/1?atlOrigin=eyJpIjoiNmU3NTI5NjZlNDc0NGRiMzk2NjE0ZWFmMTAyODAwY2MiLCJwIjoiaiJ9">The Swinburne Sigmas Jira Project</a>
        <p></p>
        <a href="mailto:webtechprojectteam@gmail.com">Contact us</a>
        <p></p>
        <a href="index.php">Index</a>
        <a href="jobs.php">Jobs</a>
        <a href="apply.php">Apply</a>
        <a href="about.php">About</a>
        <a href="enhancements/enhancements.php">Admin</a>
        <a href="manage.php">Manage</a>
    </footer>
</html>