<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CyberBytes</title>
    <link rel="stylesheet" href="../styles/style.css">
</head>
<body>
    <header class="site-header">
        <div class="logo-title">
            <img src="../images/logo.png" alt="CyberBytes Logo" class="logo-image">
            <h1>CyberBytes</h1>
        </div>

        <?php include 'nav.inc'; ?>
    </header>