<html>
<header class="site-header">
        <div class="logo-title">
            <img src="../images/logo.png" alt="CyberBytes Logo" class="logo-image">
            <h1>CyberBytes</h1>
        </div>

        <nav class="nav-links">
            <a href="index.php">Index</a>
            <a href="jobs.php">Jobs</a>
            <a href="apply.php">Apply</a>
            <a href="about.php">About</a>
            <a href="mailto:webtechprojectteam@gmail.com">Contact us</a>
        </nav>
    </header>
</html>