<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="description" content="the home page for the IT company CyberBytes" />
  <meta name="keywords" content="CyberBytes, home, info tech , web design, index" />
  <meta name="author" content="Swinburne Sigmas"  />
  <title>CyberBytes home</title>
  
  <link rel="stylesheet" href="../styles/styles.css">
</head>

<body>
    <?php include 'header.inc'?>;
    <main class= main-content>
    <!--begin text generated by open ai with prompt "create a fake it companies about page"-->
        <section class="home-box"><!--section has general info about comapany-->
            <h2>Who Are We</h2>
            <p>At Cyber BYTES, we believe in shaping the digital future—one solution at a time. we’re a full-stack IT company committed to delivering cutting-edge technology services that empower businesses to thrive in an ever-evolving digital landscape.</p>
            <h3>What We Do</h3>
            <ul>
                <li>Custom Software Development - Tailored applications that adapt to your business needs, not the other way around.</li>
                <li>UI/UX Design - Seamless digital experiences your users will love—and remember.</li>
                <li>web page design - inovative and cretive webpage to push your company into the future</li>
            </ul>
            <h3>Let’s Build the Future Together</h3>
            <p>Whether you’re a startup with a big idea or an enterprise looking to modernize, CyberBytes is your partner in digital transformation. Let’s connect and make something amazing happen.</p><!--end text generated-->
        </section>



        <section class="home-container"><!--section has images that are links as alternative way to getting to other pages-->
            <a class="home-box  home-images home-about" href="about.php"><!--each a tag contains the image as a baground and text infront. the multiple classes allowed me to modify them all simultanously and seperatly-->
                <p class="">looking to find out more about us, click here</p>
            </a>
            
            
            <a class="home-box home-images home-jobs" href="jobs.php">
                <p>wanna see what Opportunities we have available, find out here</p>
            </a>
            
            <a class="home-box home-images home-application" href="apply.php">
                <p>you ready to join the team, apply here</p>
            </a>
        
        </section>
    </main>

   <?php include 'footer.inc';?>

</body>
