<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="description" content="the home page for the IT company CyberBytes" />
  <meta name="keywords" content="CyberBytes, home, info tech , web design, index" />
  <meta name="author" content="Swinburne Sigmas"  />
  <title>CyberBytes</title>
  
  <link rel="stylesheet" href="../styles/styles.css">
</head>

<body>
    <?php include 'header.inc'?>;
    <main class= main-content>
    <!--begin text generated by open ai with prompt "create a fake it companies about page"-->
        <section class="home-box"><!--section has general info about comapany-->
            <h2>Who Are We</h2>
            <p>At Cyber BYTES, we believe in shaping the digital future—one solution at a time. we’re a full-stack IT company committed to delivering cutting-edge technology services that empower businesses to thrive in an ever-evolving digital landscape.</p>
            <h3>What We Do</h3>
            <ul>
                <li>Custom Software Development - Tailored applications that adapt to your business needs, not the other way around.</li>
                <li>UI/UX Design - Seamless digital experiences your users will love—and remember.</li>
                <li>web page design - inovative and cretive webpage to push your company into the future</li>
            </ul>
            <h3>Let’s Build the Future Together</h3>
            <p>Whether you’re a startup with a big idea or an enterprise looking to modernize, CyberBytes is your partner in digital transformation. Let’s connect and make something amazing happen.</p><!--end text generated-->
        </section>



        <section class="home-container"><!--section has images that are links as alternative way to getting to other pages-->
            <a class="home-box  home-images home-about" href="about.html"><!--each a tag contains the image as a baground and text infront. the multiple classes allowed me to modify them all simultanously and seperatly-->
                <p class="">looking to find out more about us, click here</p>
            </a>
            
            
            <a class="home-box home-images home-jobs" href="jobs.html">
                <p>wanna see what Opportunities we have available, find out here</p>
            </a>
            
            <a class="home-box home-images home-application" href="apply.html">
                <p>you ready to join the team, apply here</p>
            </a>
        
        </section>
        <br><br><br><br><br><br><br><br><br>
    </main>

    <footer class="site-footer-sticky">
        <p>Copyright 2025, The Swinburne Sigmas. All rights reserved.</p>
        <a href="https://github.com/WilkiSwin406/WebTechAssignment1" target="_blank">The Swinburne Sigmas GitHub Project</a>
        <p></p>
        <a href="https://webtechprojectteam.atlassian.net/jira/software/projects/SCRUM/boards/1?atlOrigin=eyJpIjoiNmU3NTI5NjZlNDc0NGRiMzk2NjE0ZWFmMTAyODAwY2MiLCJwIjoiaiJ9">The Swinburne Sigmas Jira Project</a>
        <p></p>
        <a href="mailto:webtechprojectteam@gmail.com">Contact us</a>
        <p></p>
        <a href="index.html">Index</a>
        <a href="jobs.html">Jobs</a>
        <a href="apply.html">Application</a>
        <a href="about.html">About</a>
        <a href="manage/manage.php"a>manage</a>
    </footer>

</body>
